### ISSUE TITLE
inconsistent indentation for switch cases

### ISSUE THREAD

**Issue by jwakely** [mattkretz/vim-gnuindent#1]
```c++
void f(int i)
{
  switch (i)
  {
    case 1:
      g(i);
    return 0;
    case 2:
    case 3:
	  ++i; // misaligned after two cases
	  break;
    case 4:
    case 5:
      // indented by hand, but gets auto-indented when I type foo(
    }
}
```

As you can see, the `return 0;` in the first case isn't aligned to the previous line.

When there are two consecutive cases, the next statement is indented too far.

Finally (and probably not restricted to `case` statements) when a comment has been incorrectly indented by the script and then manually corrected, it gets re-auto-indented when you type something that looks like code. In the example above I hit <key>Enter</key> after the `case 5:` label, then <key>Backspace</key> to get it right, but as soon as I type the opening `(` the comment jumps back to the excessive indentation.

**Comment by mattkretz** [comment]
Fixed.

The reason why typing ( triggers indenting is that `SetupGnuIndent` sets `indentkeys` to contain '('. It's necessary for lines where the ( determines a different indent for code. I currently have no idea how to make that less annoying other than making the plugin indent perfectly :wink:
